const mock_latlng = {
    lat: 42.3982347913475,
    lng: -83.11564922332765,
};
const mock_request =
    'https://developer.nrel.gov/api/alt-fuel-stations/v1/nearest.json?fuel_type=ELEC&latitude=42.3982347913475&longitude=-83.11564922332765&limit=10&api_key=HAQFREe6hJSCWohlYRVoVWec9VxprGImUc1diUCl';
const mock_response = {
    latitude: 42.3982347913475,
    longitude: -83.11564922332765,
    location_country: null,
    precision: null,
    station_locator_url: 'http://www.afdc.energy.gov/afdc/locator/stations/',
    total_results: 30,
    station_counts: {
        total: 52,
        fuels: {
            BD: {
                total: 0,
            },
            E85: {
                total: 0,
            },
            ELEC: {
                total: 52,
                stations: {
                    total: 30,
                },
            },
            HY: {
                total: 0,
            },
            LNG: {
                total: 0,
            },
            CNG: {
                total: 0,
            },
            LPG: {
                total: 0,
            },
        },
    },
    offset: 0,
    fuel_stations: [
        {
            access_code: 'public',
            access_days_time: '24 hours daily; visitor pass required',
            access_detail_code: null,
            cards_accepted: null,
            date_last_confirmed: '2020-11-09',
            expected_date: null,
            fuel_type_code: 'ELEC',
            groups_with_access_code: 'Public',
            id: 43253,
            open_date: '2012-05-03',
            owner_type_code: 'T',
            status_code: 'E',
            station_name: 'University of Detroit Mercy',
            station_phone: '313-993-1234',
            updated_at: '2020-11-09T16:53:32Z',
            facility_type: 'COLLEGE_CAMPUS',
            geocode_status: 'GPS',
            latitude: 42.41423,
            longitude: -83.1364,
            city: 'Detroit',
            intersection_directions:
                "Regular parking spaces (fifth through eighth) north of handicapped parking spaces along western face of Calihan Hall by building's western emergency exit.",
            plus4: null,
            state: 'MI',
            street_address: '4001 W McNichols Rd',
            zip: '48221',
            country: 'US',
            bd_blends: null,
            cng_dispenser_num: null,
            cng_fill_type_code: null,
            cng_psi: null,
            cng_renewable_source: null,
            cng_total_compression: null,
            cng_total_storage: null,
            cng_vehicle_class: null,
            e85_blender_pump: null,
            e85_other_ethanol_blends: null,
            ev_connector_types: ['J1772'],
            ev_dc_fast_num: null,
            ev_level1_evse_num: null,
            ev_level2_evse_num: 2,
            ev_network: 'Non-Networked',
            ev_network_web: null,
            ev_other_evse: null,
            ev_pricing: 'Free',
            ev_renewable_source: null,
            hy_is_retail: null,
            hy_pressures: null,
            hy_standards: null,
            hy_status_link: null,
            lng_renewable_source: null,
            lng_vehicle_class: null,
            lpg_primary: null,
            lpg_nozzle_types: null,
            ng_fill_type_code: null,
            ng_psi: null,
            ng_vehicle_class: null,
            access_days_time_fr: null,
            intersection_directions_fr: null,
            bd_blends_fr: null,
            groups_with_access_code_fr: 'Public',
            ev_pricing_fr: null,
            distance: 1.53152,
            distance_km: 2.46474,
        },
        {
            access_code: 'private',
            access_days_time:
                'Employee and official visitor use only, 24 hours daily with employee security badge',
            access_detail_code: null,
            cards_accepted: null,
            date_last_confirmed: '2020-10-09',
            expected_date: null,
            fuel_type_code: 'ELEC',
            groups_with_access_code: 'Private',
            id: 40599,
            open_date: '2011-06-01',
            owner_type_code: 'T',
            status_code: 'E',
            station_name: 'DTE Energy - Caniff Service Center',
            station_phone: null,
            updated_at: '2020-10-09T12:41:43Z',
            facility_type: 'UTILITY',
            geocode_status: 'GPS',
            latitude: 42.395383,
            longitude: -83.074263,
            city: 'Detroit',
            intersection_directions:
                'Northwest corner of the intersection of Caniff Street and Russell Street; two units at far right front/southeast corner of main building by large blue containers.',
            plus4: null,
            state: 'MI',
            street_address: '1201 Caniff St',
            zip: '48211',
            country: 'US',
            bd_blends: null,
            cng_dispenser_num: null,
            cng_fill_type_code: null,
            cng_psi: null,
            cng_renewable_source: null,
            cng_total_compression: null,
            cng_total_storage: null,
            cng_vehicle_class: null,
            e85_blender_pump: null,
            e85_other_ethanol_blends: null,
            ev_connector_types: ['J1772'],
            ev_dc_fast_num: null,
            ev_level1_evse_num: null,
            ev_level2_evse_num: 2,
            ev_network: 'Non-Networked',
            ev_network_web: null,
            ev_other_evse: null,
            ev_pricing: null,
            ev_renewable_source: null,
            hy_is_retail: null,
            hy_pressures: null,
            hy_standards: null,
            hy_status_link: null,
            lng_renewable_source: null,
            lng_vehicle_class: null,
            lpg_primary: null,
            lpg_nozzle_types: null,
            ng_fill_type_code: null,
            ng_psi: null,
            ng_vehicle_class: null,
            access_days_time_fr: null,
            intersection_directions_fr: null,
            bd_blends_fr: null,
            groups_with_access_code_fr: 'Privé',
            ev_pricing_fr: null,
            distance: 2.12645,
            distance_km: 3.42219,
        },
        {
            access_code: 'public',
            access_days_time: '24 hours daily',
            access_detail_code: null,
            cards_accepted: null,
            date_last_confirmed: '2021-02-02',
            expected_date: null,
            fuel_type_code: 'ELEC',
            groups_with_access_code: 'Public',
            id: 172194,
            open_date: null,
            owner_type_code: null,
            status_code: 'E',
            station_name: 'BEDROCK NEW CENTER 1',
            station_phone: '888-758-4389',
            updated_at: '2021-02-02T00:21:20Z',
            facility_type: null,
            geocode_status: 'GPS',
            latitude: 42.371338,
            longitude: -83.076242,
            city: 'Detroit',
            intersection_directions: null,
            plus4: null,
            state: 'MI',
            street_address: '116 Lothrop Rd',
            zip: '48202',
            country: 'US',
            bd_blends: null,
            cng_dispenser_num: null,
            cng_fill_type_code: null,
            cng_psi: null,
            cng_renewable_source: null,
            cng_total_compression: null,
            cng_total_storage: null,
            cng_vehicle_class: null,
            e85_blender_pump: null,
            e85_other_ethanol_blends: null,
            ev_connector_types: ['J1772'],
            ev_dc_fast_num: null,
            ev_level1_evse_num: null,
            ev_level2_evse_num: 2,
            ev_network: 'ChargePoint Network',
            ev_network_web: 'http://www.chargepoint.com/',
            ev_other_evse: null,
            ev_pricing: null,
            ev_renewable_source: null,
            hy_is_retail: null,
            hy_pressures: null,
            hy_standards: null,
            hy_status_link: null,
            lng_renewable_source: null,
            lng_vehicle_class: null,
            lpg_primary: null,
            lpg_nozzle_types: null,
            ng_fill_type_code: null,
            ng_psi: null,
            ng_vehicle_class: null,
            access_days_time_fr: null,
            intersection_directions_fr: null,
            bd_blends_fr: null,
            groups_with_access_code_fr: 'Public',
            ev_pricing_fr: null,
            ev_network_ids: {
                station: ['USCPIL131405'],
                posts: ['172861', '172863'],
            },
            distance: 2.74092,
            distance_km: 4.41108,
        },
    ],
};

module.exports = {
    mock_latlng,
    mock_request,
    mock_response,
};
